### ISSUE TITLE
How to deal with user embeddings?

### ISSUE THREAD

**Issue by followingjoneses** [yongqyu/poi2vec#1]
Is that the same way like word2vec ? e.g. hierarchical softmax? 
Thank you in advance. :)

**Comment by yongqyu** [comment]
The user embedding of poi2vec does not exactly match word2vec, but it is a similar principle.
For the detailed principle, it is good to refer to Equation 6 of the paper.

**Comment by followingjoneses** [comment]
I see. Thank you.
