### ISSUE TITLE
For every POI the route count is always 4.

### ISSUE THREAD

**Issue by followingjoneses** [yongqyu/poi2vec#2]
I notice that you set route count to be 4 in config.py, while it can be 1, 2 or 4 actually. I think that can lead to some problems in POI2VEC.forward. Suppose a POI only has 2 routes, then the 'view' function will infer -1 to 1/2 batch size.

**Comment by yongqyu** [comment]
Thank you for your interest.
I can not afford it right now, but if I have time, I will try to reflect on it.

Sorry to late.
