### ISSUE TITLE
missing id2user.npy

### ISSUE THREAD

**Issue by LuckyDoggy** [yongqyu/poi2vec#3]
I download the codes and try to run it.But it seems that you didn't upload the code to generate id2user.npy. Could you help me to run it? Thank you.

**Comment by yongqyu** [comment]
[poi2vec/ipynb/preprocess2.ipynb](https://github.com/yongqyu/poi2vec/blob/master/ipynb/preprocess2.ipynb) is the file that creates id2user.npy.
I apologize that the code is not neatly organized.

Thanks.
