### ISSUE TITLE
Performance compare to the paper implementation and Readme

### ISSUE THREAD

**Issue by rahmanidashti** [yongqyu/poi2vec#5]
Hi,

Regarding the performance of your implementation compare to the paper result, is it same as the paper? Also, could you please provide a readme file of details and running the code?

Thanks,
Saeed

**Comment by yongqyu** [comment]
Hi, again.

It is unlikely that there was a large performance difference between the two performances.
I will make the readme file if I can afford it, but I think it will be difficult for the time being.
I'm sorry about that.

Thanks.
