### ISSUE TITLE
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.

### ISSUE THREAD

**Issue by youngflyasd** [yongqyu/poi2vec#6]
When I run the train.py, I had the problem.
File "train.py", line 59, in run
    context = Variable(torch.from_numpy(np.asarray(context)).type(ltype))
TypeError: can't convert np.ndarray of type numpy.object_. The only supported types are: float64, float32, float16, int64, int32, int16, int8, and uint8.
I still can not  convert the context to the right format for tensor after I have try many ways.  I hope for your help.

**Comment by yongqyu** [comment]
Hi, young.
First of all, thank you for your interest in my implementation.
I'm wondering what ltype, the type argument, is.

I use mainly function `.to()` instead of `.type()`.
And now you do not have to use Variable in pytorch 1.0 or later.

Thanks.

**Comment by youngflyasd** [comment]
Thanks for your reply.
the definition of ltype is in the config.py , ltype = torch.cuda.LongTensor. 
I test the function .to() and do not use the Variable just now, but the same problem still exist.  
The type of context is tuples of lists, I can not convert it to Tensor. but "user = Variable(torch.from_numpy(np.asarray(user)).type(ltype))" works in the same place, the type of user is tuples.

**Comment by yongqyu** [comment]
So in my opinion, `context` seems to be a list of lists that are not of the same length.
Please check the length.
Thank you.

**Comment by youngflyasd** [comment]
Yes，just like you said, context is a list of lists. I have used "0" to pad the context through function np.pad().
 It works fine after the modification of context, but I do not know if it is the right thing to pad the context like that.  
Thanks.

**Comment by yongqyu** [comment]
I think there is no problem with zero padding due to the characteristic of the operation.
Thank you.
