### ISSUE TITLE
hello ，i have some questiones for you

### ISSUE THREAD

**Issue by fllxh** [yongqyu/poi2vec#7]
when i ues your code，it occured me a question
FileNotFoundError: [Errno 2] No such file or directory: './npy/id2poi.npy'
i want know where the file and how i can get the data

**Comment by yongqyu** [comment]
I apologize for not clean up the code.
Perhaps the code you are looking for can be found in 
https://github.com/yongqyu/poi2vec/blob/master/ipynb/preprocess2.ipynb.
I'm not working on this now, so the more specific answer seems difficult.
Thank you.

**Comment by fllxh** [comment]
thank you for your reply ,I am glad to you give me some choice to save my problem



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yongqyu"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 上午9:57
收件人:&nbsp;"yongqyu/poi2vec"<poi2vec@noreply.github.com&gt;;
抄送:&nbsp;"狗  东西"<547230276@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [yongqyu/poi2vec] hello ，i have some questiones for you (#7)




I apologize for not clean up the code.
 Perhaps the code you are looking for can be found in
 https://github.com/yongqyu/poi2vec/blob/master/ipynb/preprocess2.ipynb.
 I'm not working on this now, so the more specific answer seems difficult.
 Thank you.
